add quartz #7
edu-xored/memorise pull request #44
Opened 2016-10-31 12:29 UTC by DVEfremov

2016-10-31 12:29 UTC, DVEfremov commented
Looks ok for me

2016-10-31 12:35 UTC, sumboid requested changes

2016-10-31 12:35 UTC, sumboid commented on memorise-web-app/src/main/java/org/xored/edu/memorise/QuartzJob.java
> + * Created by firix on 10/31/16.
Think we don't need comments with creator info

2016-10-31 16:01 UTC, aonnikov approved these changes

2016-11-01 06:32 UTC, sumboid approved these changes

2016-11-01 10:46 UTC, merged