finish setup quartz triggers and launching quartz job manually
edu-xored/memorise pull request #66
Opened 2016-11-19 07:34 UTC by Firix-Pavel

Запуск краулера теперь доступен только Publisher'у. Автоматический запуск краулера происходит теперь каждые 10 минут по требованию @DVEfremov. Пока не понятно что краулить, поэтому запускается тестовая задача для краулера. Думаю, реализацию запуска краулера с требованиями нужно выделить в отдельную задачу. Жду замечаний.

2016-11-19 13:56 UTC, sumboid requested changes

2016-11-19 13:56 UTC, sumboid commented on memorise-web-app/src/main/webapp/js/app.js
> +		    alert('You run Crawler');
Мне кажется, что alert с сообщением лучше вынести в хендлеры success и error, которые чуть ниже, и писать сообщение не только об успешном старте, но и о том, что произошла ошибка.

Причем error скорее всего вызывает хендлер с объектом с инфой об ошибке, что тоже стоит учитывать.

Ну и на будущее: оповещение пользователя о событиях в приложении алертами -- это не очень хороший стиль, но так как у нас на фронте сейчас, скорее всего, ничего лучше нет, то для демки пойдет.

2016-11-19 13:56 UTC, sumboid commented on memorise-web-app/src/main/webapp/index.html
>  					<li><a href="" ng-click="Crawler()"> Crawler</a></li>
Ссылки и кнопки, которые приводят к действиям, которые длятся какое-то время (например, rest-запрос, ответ от сервера не может прилететь мгновенно), стоит блокировать на время, пока ответ не был получен. Но для демки это не критично, поэтому это можно отнести к FYI и оставить все как есть.

2016-11-20 05:56 UTC, Firix-Pavel commented on memorise-web-app/src/main/webapp/index.html
>  					<li><a href="" ng-click="Crawler()"> Crawler</a></li>
Сделал ее неактивной, но визуально это не видно. Нужно "Crawler" переделать в полноценный button, наверное.

2016-11-20 06:01 UTC, sumboid requested changes

2016-11-20 06:01 UTC, sumboid commented on memorise-web-app/src/main/webapp/js/app.js
> +		        .error(function(){
Вот тут стоит передавать не `function(){ ... }`, а `function(response) { ... }`. 
[https://docs.angularjs.org/api/ng/service/$http ](https://docs.angularjs.org/api/ng/service/$http) -- в соответствии с описанием, `response` будет объектом со следующими полями:

> data – {string|Object} – The response body transformed with the transform functions.
> status – {number} – HTTP status code of the response.
> headers – {function([headerName])} – Header getter function.
> config – {Object} – The configuration object that was used to generate the request.
> statusText – {string} – HTTP status text of the response.
> 

И было бы полезно в алерте сразу увидеть `response.status` и `response.statusText`, чтобы было понятно, что произошло.

2016-11-20 06:03 UTC, sumboid commented
И вообще возник такой вопрос -- что сейчас будет происходить, если мы попытаемся запустить crawler в момент, когда у нас есть незавершенная джоба? Не стоит ли нам ограничивать количество одновременно запущенных кравлеров?

2016-11-20 06:18 UTC, Firix-Pavel commented
Сложно сказать, так как нормального запуска cralwler'а пока нет. В данный момент одновременно только один crawler должен быть запущен. Но может получится, что crawler будет запущен вручную и по расписаню одновременно.

2016-11-20 06:27 UTC, sumboid commented
Окей, я тогда заведу попозже issue на эту тему, а в этом pr этого учитывать не нужно.

2016-11-20 07:35 UTC, sumboid approved these changes

2016-11-20 17:11 UTC, DVEfremov commented
Если есть проблемы с одновременной работой процесса то нужно добавлять писсимистичную
писсимистичную offline блокировку типа 
LockByObject<Memo>

2016-11-20 17:28 UTC, DVEfremov requested changes

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java
> +        seeds.add("http://the-flow.ru/videos/yelawolf-shadows/");
[major] магические константы нужно вынести в настройки или хотя бы в константы

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java
> +            //TODO: handle exception
[major] нельзя оставлять пустой кетч, нужно выбрать стратегию обработки ошибок 
* добавить лог и проброс дальше exception
* трансляция исключения в свою MemoProcessingException проброс dапликаи

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java
> +        crawlConfig.setCrawlStorageFolder("src/resources/test/crawlerTemporaryDirectory");
[major] магическая константа

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java
> +        crawlConfig.setMaxDepthOfCrawling(1);
[major] магическая константа

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/MemoCrawlerJob.java
> +        crawlConfig.setMaxPagesToFetch(1);
[major] магическая константа

2016-11-20 17:28 UTC, DVEfremov commented on memorise-web-app/src/main/resources/context.xml
> -		<property name="cronExpression" value="0 0 3 * * ?" />
[minor] лучше организотьва property file и вынести все туда и сделать сервис по работе с проперти файлом

2016-11-22 08:44 UTC, Firix-Pavel commented
Объединил с issue-68. Так как никто не ответил, сделал как предлагал в задаче 68.

@sumboid 
Кнопку "Crawler" сделать неактивной после нажатия не получается, так как CrawlerJob у нас асинхронная. После http запроса клиента ему сразу возвращается ответ, была ли успешно запущена работа или нет, узнать когда она завершится он не может.

2016-11-22 13:20 UTC, Firix-Pavel commented on memorise-web-app/src/main/resources/context.xml
> -		<property name="cronExpression" value="0 0 3 * * ?" />
Может создание сервиса и проперти файла вынести в отдельную issue?

2016-11-23 03:59 UTC, sumboid commented
@Firix-Pavel 
Так её же надо делать неактивной в момент времени, когда мы еще не получили ответ. Ну то есть может же всякое случиться, и ответ может идти, например, несколько секунд. Или у нас навесится какая-нибудь логика (чисто гипотетически) на старте crawler.
Пользователю, как минимум, не надо давать жамкать кнопку много раз, чтобы он потом не получил кучу ошибок запуска в ответ. А по-хорошему, можно еще как-нибудь визуализировать процесс старта: например, прикрутить спиннер на той же неактивной кнопке, чтобы сразу стало понятно, что что-то происходит.

Так что я предлагаю делать кнопку неактивной так же, как и раньше это делалось: [commit fb32f55b](https://github.com/edu-xored/memorise/pull/66/commits/fb32f55b6b2a286d0a3088cce39462070914bb15). Только я просмотрел один момент -- кнопку надо делать активной после того, как какой-нибудь из хендлеров (success или error) сработает. Например, перед alert.

2016-11-23 06:03 UTC, sumboid requested changes

2016-11-23 06:03 UTC, sumboid commented on memorise-web-app/src/main/webapp/index.html
> +				<li><a href="" ng-click="Crawler()"> Crawler</a></li>
Тут точно не пропущено `ng-click="crawlBtnIsDisabled || Crawler()" ng-disabled="crawlBtnIsDisabled"`?
Просто до этого такая штука присутствовала.

2016-11-23 06:07 UTC, Firix-Pavel commented on memorise-web-app/src/main/webapp/index.html
> +				<li><a href="" ng-click="Crawler()"> Crawler</a></li>
ой

2016-11-24 03:30 UTC, sumboid approved these changes

2016-11-26 07:17 UTC, Firix-Pavel commented
Почему PR не заапрувлен и не замержен, есть какие-то замечания?

2016-11-26 09:56 UTC, aonnikov approved these changes

2016-11-26 13:54 UTC, DVEfremov approved these changes

2016-11-27 07:56 UTC, merged