added registration
edu-xored/memorise pull request #67
Opened 2016-11-19 11:01 UTC by Rhymmor

#52

2016-11-20 03:47 UTC, aonnikov approved these changes
Было бы неплохо добавить немного валидации для имени пользователя и пароля и корректно отобразить результат (сейчас, например я получаю "POST on rest/user/register failed with status 500" если пользователь с таким именем уже существует). Можно рассматривать это как улучшение

2016-11-20 09:37 UTC, Rhymmor commented
А как именно валидировать имя и пароль?

2016-11-20 10:22 UTC, aonnikov commented
Тут можно много всего придумать. Можно ограничить минимальную и максимальную длину (как имени, так и пароля), множество разрешенных символов и т.д.
Как минимум, нужно сделать так, чтобы нельзя было зарегистрироваться с пустым именем пользователя и паролем. Нужно корректно обработать ситуацию, когда пользователь с таким именем уже существует.

2016-11-20 17:06 UTC, DVEfremov requested changes

2016-11-20 17:06 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/rest/resources/UserResource.java
> +		User userUser = new User(username, this.passwordEncoder.encode(password));
[minor] userUser -> user

2016-11-20 17:06 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/rest/resources/UserResource.java
> +		//return authenticate(username, password);
[normal] мусор вычищаем

2016-11-20 17:06 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/rest/resources/UserResource.java
> +		this.userDao.save(userUser);
[major] DAO не используется на уровне open Api доступ к данным должен быть инкапуслирован в реализации соотвествующего сервиа  и быть package private
п

2016-11-21 13:25 UTC, Rhymmor commented on memorise-web-app/src/main/java/org/xored/edu/memorise/rest/resources/UserResource.java
> +		this.userDao.save(userUser);
Реализация этой логики была сделана на базе уже готового кода из класса JournalEntryResource. Пример: 
```
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Memo create(Memo journalsEntry) {
	this.logger.info("create(): " + journalsEntry);
	return this.journalEntryDao.save(journalsEntry);
}
```
Почему здесь не приемлемо использование DAO? Мы ведь не делаем никакой особой бизнес-логики в методе, а лишь сохраняем сущность в бд. Разве это не должно делать дао? Если реализовывать это в отдельном сервисе, то чем сервис будет отличаться от дао?

Предлагаю провести рефакторинг после демо в рамках отдельной задачи, а пока оставить так.

2016-11-22 09:20 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/rest/resources/UserResource.java
> +		this.userDao.save(userUser);
[minor] То как было - это самый лучший пример, рефакторинг в отдельной задаче норм, но обычно как таким комментам уже нужно прикладывать нормер задачи где уже описано как будет решаться подобный тех долг

сервисный слой даже с простым  делигированием к дао дает возможность писать модульный тесты вместо интеграционных ...

2016-11-22 09:20 UTC, DVEfremov approved these changes

2016-11-22 09:20 UTC, merged