Linked crawler with database
edu-xored/memorise pull request #83
Opened 2016-11-26 11:21 UTC by Rhymmor

Краулер теперь добавляет в бд нашедший мем или обновляет, если он уже есть. Добавлен базовый сервис с операцией сохранения и удаления, чтобы не работать напрямую с дао. Все сервисы перемещены в в отдельный пакет api/memo/services.

2016-11-26 11:55 UTC, Rhymmor commented
Есть вопрос по моей реализации. В задаче #81 я описал вопрос. В итоге я сделал несколько сервиcов, но из-за этого получились довольно перегруженными своими параметрами классы `ActionCrawler` и `CrawlerRunner`. Может есть решение лучше, чем это?

2016-11-26 12:01 UTC, aonnikov commented
Проблема большого количества параметров решается вынесением этих параметров в отдельный класс, скажем `CrawlingContext`, который передается в `ActionCrawler` и `CrawlerRunner`.

2016-11-26 12:06 UTC, aonnikov commented
Небольшое уточнение, `CrawlingContext` должен содержать только необходимые сервисы и т.д. Данные необходимые для краулинга (искомую строку, список адресов и прочее) следует передавать в отдельном объекте.

2016-11-26 12:09 UTC, Rhymmor commented
Ну да, я уже объединял параметры краулера в класс `CrawlerSettings`, просто подумал, что проблема может быть в проектировании.

2016-11-26 12:52 UTC, aonnikov requested changes

2016-11-26 12:52 UTC, aonnikov commented on memorise-web-app/pom.xml
> +			<version>LATEST</version>
Не стоит использовать LATEST версию, особенно для сторонних зависимостей. Рлюс версию нужно вынести в properties.

2016-11-26 12:52 UTC, aonnikov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/crawler/impl/DummyMemoMatchingImpl.java
> +        if (candidate.getCounter() > 5L) {
Нужно вынести магические числа в константы

2016-11-26 12:52 UTC, aonnikov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/crawler/api/MemoParser.java
> +    void parse(String text, Memo candidate);
На мой взгялд, неудачный интерфейс. Его предназначение - загадка для меня. Что парсим и зачем? А как данные вернуть? Ниже в реализации интерфейса я вижу, что данные возвращаются через параметр `candidate`,  но это очень неявно.

2016-11-26 12:52 UTC, aonnikov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/impl/memo/JpaBasicMemoService.java
> +        List memosByTitle = searchMemoService.findMemosByTitle(memo.getTitle());
А давай сделаем так, чтобы `SearchMemoService.findMemosByTitle` возвращал List<Memo>?

2016-11-26 12:53 UTC, aonnikov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/impl/memo/JpaBasicMemoService.java
> +        List memosByTitle = searchMemoService.findMemosByTitle(memo.getTitle());
`List<Memo>`  я имел ввиду

2016-11-26 13:51 UTC, Rhymmor commented on memorise-web-app/src/main/java/org/xored/edu/memorise/crawler/api/MemoParser.java
> +    void parse(String text, Memo candidate);
Ну название видимо неудачное. Он нужен для того, чтобы из текста вытаскивать упоминания о  меме каким-либо образом.

2016-11-27 07:55 UTC, aonnikov approved these changes

2016-11-27 07:55 UTC, aonnikov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/crawler/CrawlerServicesContext.java
> +    @Autowired
А зачем здесь `@Autowired`?

2016-11-28 00:48 UTC, merged