Property file
edu-xored/memorise pull request #84
Opened 2016-11-27 08:10 UTC by Firix-Pavel

Добавил простой PropertyReader для чтения application.properties (пока что только для quartz).
Думаю добавить Apache commons configuartion для релоада пропертей в рантайме.
Жду замечаний.

2016-11-27 14:08 UTC, sumboid requested changes

2016-11-27 14:08 UTC, sumboid commented on memorise-web-app/src/main/java/org/xored/edu/memorise/PropertyReader.java
> +		System.out.println(quartzTriggerTime);
Не будет лучше логировать это через `logger.info()`? Причем добавить побольше инфы.

2016-11-27 14:08 UTC, sumboid commented on memorise-web-app/src/main/java/org/xored/edu/memorise/PropertyReader.java
> +		TriggerBuilder<CronTrigger> tb = oldTrigger.getObject().getTriggerBuilder();
`tb` не очень говорящее имя переменной, лучше переименовать во что-нибудь более читаемое, например, `triggerBuilder`.

2016-11-27 14:08 UTC, sumboid commented on memorise-web-app/src/main/resources/application.properties
> +quartz.time = 0 0/10 * * * ?
Не хватает пустой строки

2016-11-27 14:08 UTC, sumboid commented on memorise-web-app/src/main/resources/context.xml
> +		<property name="cronExpression" value="0 0 3 * * ?" />
Как и где сейчас эта проперти используется?
Просто смущает то, что появилась такая штука:
```
quartz.time = 0 0/10 * * * ? 
```
И существует она одновременно со значением `0 0 3 * * ?`

2016-11-27 14:58 UTC, Firix-Pavel commented on memorise-web-app/src/main/resources/application.properties
> +quartz.time = 0 0/10 * * * ?
fix

2016-11-27 14:59 UTC, Firix-Pavel commented on memorise-web-app/src/main/resources/context.xml
> +		<property name="cronExpression" value="0 0 3 * * ?" />
Просто бин фабрики триггеров без строки cronExpression создать не получается, поэтому оставил значение по умолчанию, как сделать лучше не знаю.

2016-11-28 03:43 UTC, sumboid approved these changes

2016-11-28 14:48 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/PropertyReader.java
> +	private CronTriggerFactoryBean oldTrigger;
[question]  oldTrigger не понятно что есть такое и для чего

2016-11-28 14:48 UTC, DVEfremov commented on memorise-web-app/src/main/java/org/xored/edu/memorise/PropertyReader.java
> +public class PropertyReader {
[normal] если этот ридер только для того чтобы зачитывать расписание quartz job то стоит егшо так и называть иначе можно подумать что он универсальный

2016-11-28 14:48 UTC, DVEfremov commented on memorise-web-app/src/main/resources/context.xml
> +		<property name="cronExpression" value="0 0 3 * * ?" />
ок оставим пока так 
рестрт нужен чтобы перешедулить после изменния файла  ?

2016-11-28 14:48 UTC, merged